import argparse

parser=argparse.ArgumentParser()
parser=argparse.ArgumentParser(
    description='$ python vel2temp.py -v VELOCITY_FILE -a ATOM -e ENERGY_FILE -t "b", "mp"> OUTPUT')
parser.add_argument('-v', '--velocity_file', help='File with atomic velocities generated by tra2vel.py',type=str)
parser.add_argument('-a', '--atom', help='Atomic symbol of the element of interest',type=str)
parser.add_argument('-e', '--energy_file', help='Energy file generated by CPMD',type=str)
parser.add_argument('-t', '--temperature', help='Method for temperature.  The options are: b, to get it fitting a MB distribution; mp, to calculate it from the most frequent velocity; and mean, to calculate the temperature from the mean velocity',type=str)
args=parser.parse_args()
velocity_file=str(args.velocity_file)
element=str(args.atom)
energy_file=str(args.energy_file)
TempMet=str(args.temperature)

in_file = list()
input_file = open(velocity_file, 'r')
for i in input_file:
        in_file.append(i.replace('\n',''))
input_file.close()

atoms =int(in_file[0]) # total amount of atoms
steps=int(len(in_file)/(atoms+2))

#### List of atomic masses #############
Da_me=1822.888486209
atomic_mass={
'H': 1,
'He': 4.,
'Li': 7.,
'Be': 9.,
'B': 11.,
'C': 12.,
'N': 14.,
'O': 16.,
'F': 19.,
'Ne': 20.,
}
if element == 'water':
        element='O'
        atomic_mass[element]=18.

#### Save matrix of velocities of the specified element ####
velocity_matrix=list()
kinetic_energy=list()
for step in range (steps):
        velocity_list=list()
        kin_ene=0
        for atom in range (atoms):
                line=in_file[step*(atoms+2)+(atom+2)].split()
                kin_ene+=atomic_mass[line[0]]*Da_me*float(line[1])**2/2
                if line[0]==element:
                        velocity_list.append(float(line[1]))
        kinetic_energy.append(kin_ene) 
        velocity_matrix.append(velocity_list)
if len(velocity_matrix[0])==0:
        print ('The element '+element+' is not in this file :(')
        exit()
in_file=list()

#### Fit MB distribution and calculate temperature ####
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

maxwell = stats.maxwell

vel_matrix=np.array(velocity_matrix)	# shape=(steps, #of atoms)
velocity_matrix=list()
atoms=len(vel_matrix[0])		# update #of atoms
vel_max=np.amax(vel_matrix)

m_k=atomic_mass[element]*Da_me/3.166811563e-6    #m*me/k
Temp=np.zeros((steps,2))

#### Fit MB distribution and calculate temperature ####
if TempMet == 'b':		# In Maxwell-Boltzmann distribution, b=m/2kT
        for i in range(steps):
                dist_fit=maxwell.fit(vel_matrix[i], floc=0)  #output parameter a =sqrt(kT/m)
                Temp[i][0]=(i+1)
                Temp[i][1]=(dist_fit[1]**2*m_k*3/2)	#T=a^2*m/k*3

#### Calculate temperature from the most probable (or repeated) velocity ####
elif TempMet == 'mp':
        from scipy.stats import mode
        vel_N=11
        for i in range(steps):
                step_norm=vel_matrix[i]/max(vel_matrix[i])
                norm_mode=mode(np.around(step_norm*vel_N/100,2))
                v_mp=norm_mode[0]*100/vel_N*max(vel_matrix[i])
                Temp[i][0]=(i+1)
                Temp[i][1]=(m_k*v_mp**2/2)*3	# T=(mv^2)/(2k)*3

#### Calculate temperature from the mean velocity ####
elif TempMet == 'mean':
        for i in range(steps):
                dist_fit=maxwell.fit(vel_matrix[i], floc=0)  #output parameter a =kT/m
                v_mean=maxwell.mean(*dist_fit)
                Temp[i][0]=(i+1)
                Temp[i][1]=(v_mean**2*3.1415926535*m_k/8)*3	# T=(pi*m*v^2)/(8k)

#plt.plot(Temp[:,0], Temp[:,1], linewidth=1, color='crimson')
#plt.xlabel ('Time [ps]')
#plt.ylabel ('Translational temperature [K]')
#plt.xlim(0, )
#plt.ylim(0, )
#plt.hist(vel_matrix[-1], bins=11, density=True)
#x = np.linspace(0, vel_max,50)
#plt.plot(x, maxwell.pdf(x, *dist_fit), lw=2)
#plt.show()

#### Generate energy file with the aditional column ####
ene_file = open(energy_file, 'r')

ene_lines=list()
for i in range (10):
        ene_lines.append(ene_file.readline())
T_index=0

for line in ene_file:
        ene_lines=list()
        ene_lines.append(line.replace('\n','').split())
        while ene_lines[-1][0][-1]!='0':
                ene_lines.append(ene_file.readline().replace('\n','').split())
        data_out=np.zeros((10,1))
        for i in ene_lines:
                data_out[1]+=float(i[1])
                data_out[2]+=float(i[2])
                data_out[3]+=float(i[3])
                data_out[4]+=float(i[4])
                data_out[5]+=float(i[5])
                data_out[8]+=float(i[6])
                data_out[9]+=float(i[7])
        data_out=data_out/len(ene_lines)
        data_out[0]=ene_lines[0][0]
        data_out[6]=Temp[T_index][1]
        data_out[7]=kinetic_energy[T_index]
        T_index+=1
        text=' '*(8-len(str(int(data_out[0][0]))))+str(int(data_out[0][0]))	# Col 1
        text+=' '*(12-len(str(round(data_out[1][0],8))))+str(round(data_out[1][0],8))	# Col 2
        text+=' '*(10-len(str(round(data_out[2][0],3))))+str(round(data_out[2][0],3))	# Col 3
        text+=' '*(18-len(str(round(data_out[3][0],10))))+str(round(data_out[3][0],10))	# Col 4
        text+=' '*(18-len(str(round(data_out[4][0],10))))+str(round(data_out[4][0],10))	# Col 5
        text+=' '*(18-len(str(round(data_out[5][0],10))))+str(round(data_out[5][0],10))	# Col 6
        text+=' '*(12-len(str(round(data_out[6][0],3))))+str(round(data_out[6][0],3))	# Boltzmann Temperature
        text+=' '*(18-len('{:.8e}'.format(data_out[7][0])))+'{:.8e}'.format(data_out[7][0])
        text+=' '*(14-len('{:.5e}'.format(data_out[8][0])))+'{:.5e}'.format(data_out[8][0])
        text+=' '*(8-len(str(round(data_out[9][0],2))))+str(round(data_out[9][0],2))
        print(text)
ene_file.close()
